// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Datafy endpoint. Can also be configured using the `DATAFY_ENDPOINT` environment variable. Defaults to `https://api.datafy.io`.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "datafy:endpoint")
}

// Datafy token. Can also be configured using the `DATAFY_TOKEN` environment variable.
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "datafy:token")
}
