version: "2"

run:
  concurrency: 1
  go: '1.24'
  relative-path-mode: cfg
  # Don't analyse code with the "go:build !codeanalysis" tag.
  # Mostly used for snapshots, which we want to skip altogether.
  build-tags:
    - codeanalysis


formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

linters:
  # Default, see https://golangci-lint.run/usage/linters/#enabled-by-default
  default: standard
  enable:
    - cyclop
    - errname
    # - gosimple
  settings:
    cyclop:
      # The maximal code complexity to report.
      # Default: 10
      max-complexity: 15
  exclusions:
    generated: strict
