// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datafy
{
    public static class GetRoleArn
    {
        /// <summary>
        /// Retrieves a specific Datafy role ARN.
        /// </summary>
        public static Task<GetRoleArnResult> InvokeAsync(GetRoleArnArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRoleArnResult>("datafy:index/getRoleArn:getRoleArn", args ?? new GetRoleArnArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific Datafy role ARN.
        /// </summary>
        public static Output<GetRoleArnResult> Invoke(GetRoleArnInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleArnResult>("datafy:index/getRoleArn:getRoleArn", args ?? new GetRoleArnInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific Datafy role ARN.
        /// </summary>
        public static Output<GetRoleArnResult> Invoke(GetRoleArnInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRoleArnResult>("datafy:index/getRoleArn:getRoleArn", args ?? new GetRoleArnInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRoleArnArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        public GetRoleArnArgs()
        {
        }
        public static new GetRoleArnArgs Empty => new GetRoleArnArgs();
    }

    public sealed class GetRoleArnInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        public GetRoleArnInvokeArgs()
        {
        }
        public static new GetRoleArnInvokeArgs Empty => new GetRoleArnInvokeArgs();
    }


    [OutputType]
    public sealed class GetRoleArnResult
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// The Amazon Resource Name (ARN) of the IAM role.
        /// </summary>
        public readonly string Arn;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetRoleArnResult(
            string accountId,

            string arn,

            string id)
        {
            AccountId = accountId;
            Arn = arn;
            Id = id;
        }
    }
}
