// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datafy
{
    public static class GetToken
    {
        /// <summary>
        /// Retrieves a specific Datafy token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datafy = Pulumi.Datafy;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Datafy.GetToken.Invoke(new()
        ///     {
        ///         AccountId = "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
        ///         TokenId = "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetTokenResult> InvokeAsync(GetTokenArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTokenResult>("datafy:index/getToken:getToken", args ?? new GetTokenArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific Datafy token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datafy = Pulumi.Datafy;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Datafy.GetToken.Invoke(new()
        ///     {
        ///         AccountId = "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
        ///         TokenId = "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetTokenResult> Invoke(GetTokenInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTokenResult>("datafy:index/getToken:getToken", args ?? new GetTokenInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a specific Datafy token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datafy = Pulumi.Datafy;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Datafy.GetToken.Invoke(new()
        ///     {
        ///         AccountId = "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
        ///         TokenId = "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetTokenResult> Invoke(GetTokenInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTokenResult>("datafy:index/getToken:getToken", args ?? new GetTokenInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTokenArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        /// <summary>
        /// The unique identifier of the Datafy token.
        /// </summary>
        [Input("tokenId", required: true)]
        public string TokenId { get; set; } = null!;

        public GetTokenArgs()
        {
        }
        public static new GetTokenArgs Empty => new GetTokenArgs();
    }

    public sealed class GetTokenInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// The unique identifier of the Datafy token.
        /// </summary>
        [Input("tokenId", required: true)]
        public Input<string> TokenId { get; set; } = null!;

        public GetTokenInvokeArgs()
        {
        }
        public static new GetTokenInvokeArgs Empty => new GetTokenInvokeArgs();
    }


    [OutputType]
    public sealed class GetTokenResult
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        public readonly string AccountId;
        /// <summary>
        /// The time when the token was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// A description of the token.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The time when the token will expire.
        /// </summary>
        public readonly string Expires;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of role IDs associated with the token.
        /// </summary>
        public readonly ImmutableArray<string> RoleIds;
        /// <summary>
        /// The unique identifier of the Datafy token.
        /// </summary>
        public readonly string TokenId;

        [OutputConstructor]
        private GetTokenResult(
            string accountId,

            string createdAt,

            string description,

            string expires,

            string id,

            ImmutableArray<string> roleIds,

            string tokenId)
        {
            AccountId = accountId;
            CreatedAt = createdAt;
            Description = description;
            Expires = expires;
            Id = id;
            RoleIds = roleIds;
            TokenId = tokenId;
        }
    }
}
