// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datafy
{
    /// <summary>
    /// Manages a Datafy role ARN, which represents an AWS IAM role associated with a Datafy account.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Datafy = Pulumi.Datafy;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Datafy.RoleArn("example", new()
    ///     {
    ///         AccountId = "5f19d868-64f2-4251-a98f-b19571d1f4e9",
    ///         Arn = "arn:aws:iam::123456789012:role/example-role",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [DatafyResourceType("datafy:index/roleArn:RoleArn")]
    public partial class RoleArn : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Output("accountId")]
        public Output<string> AccountId { get; private set; } = null!;

        /// <summary>
        /// The Amazon Resource Name (ARN) of the IAM role.
        /// </summary>
        [Output("arn")]
        public Output<string> Arn { get; private set; } = null!;


        /// <summary>
        /// Create a RoleArn resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RoleArn(string name, RoleArnArgs args, CustomResourceOptions? options = null)
            : base("datafy:index/roleArn:RoleArn", name, args ?? new RoleArnArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RoleArn(string name, Input<string> id, RoleArnState? state = null, CustomResourceOptions? options = null)
            : base("datafy:index/roleArn:RoleArn", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RoleArn resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RoleArn Get(string name, Input<string> id, RoleArnState? state = null, CustomResourceOptions? options = null)
        {
            return new RoleArn(name, id, state, options);
        }
    }

    public sealed class RoleArnArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        /// <summary>
        /// The Amazon Resource Name (ARN) of the IAM role.
        /// </summary>
        [Input("arn", required: true)]
        public Input<string> Arn { get; set; } = null!;

        public RoleArnArgs()
        {
        }
        public static new RoleArnArgs Empty => new RoleArnArgs();
    }

    public sealed class RoleArnState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique identifier of the Datafy account.
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// The Amazon Resource Name (ARN) of the IAM role.
        /// </summary>
        [Input("arn")]
        public Input<string>? Arn { get; set; }

        public RoleArnState()
        {
        }
        public static new RoleArnState Empty => new RoleArnState();
    }
}
