// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datafy

import (
	"context"
	"reflect"

	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a specific Datafy role ARN.
func LookupRoleArn(ctx *pulumi.Context, args *LookupRoleArnArgs, opts ...pulumi.InvokeOption) (*LookupRoleArnResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRoleArnResult
	err := ctx.Invoke("datafy:index/getRoleArn:getRoleArn", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRoleArn.
type LookupRoleArnArgs struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
}

// A collection of values returned by getRoleArn.
type LookupRoleArnResult struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn string `pulumi:"arn"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func LookupRoleArnOutput(ctx *pulumi.Context, args LookupRoleArnOutputArgs, opts ...pulumi.InvokeOption) LookupRoleArnResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRoleArnResultOutput, error) {
			args := v.(LookupRoleArnArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("datafy:index/getRoleArn:getRoleArn", args, LookupRoleArnResultOutput{}, options).(LookupRoleArnResultOutput), nil
		}).(LookupRoleArnResultOutput)
}

// A collection of arguments for invoking getRoleArn.
type LookupRoleArnOutputArgs struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringInput `pulumi:"accountId"`
}

func (LookupRoleArnOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRoleArnArgs)(nil)).Elem()
}

// A collection of values returned by getRoleArn.
type LookupRoleArnResultOutput struct{ *pulumi.OutputState }

func (LookupRoleArnResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRoleArnResult)(nil)).Elem()
}

func (o LookupRoleArnResultOutput) ToLookupRoleArnResultOutput() LookupRoleArnResultOutput {
	return o
}

func (o LookupRoleArnResultOutput) ToLookupRoleArnResultOutputWithContext(ctx context.Context) LookupRoleArnResultOutput {
	return o
}

// The unique identifier of the Datafy account.
func (o LookupRoleArnResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleArnResult) string { return v.AccountId }).(pulumi.StringOutput)
}

// The Amazon Resource Name (ARN) of the IAM role.
func (o LookupRoleArnResultOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleArnResult) string { return v.Arn }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupRoleArnResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleArnResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRoleArnResultOutput{})
}
