// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datafy

import (
	"context"
	"reflect"

	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves a specific Datafy token.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := datafy.LookupToken(ctx, &datafy.LookupTokenArgs{
//				AccountId: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
//				TokenId:   "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupToken(ctx *pulumi.Context, args *LookupTokenArgs, opts ...pulumi.InvokeOption) (*LookupTokenResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTokenResult
	err := ctx.Invoke("datafy:index/getToken:getToken", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getToken.
type LookupTokenArgs struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
	// The unique identifier of the Datafy token.
	TokenId string `pulumi:"tokenId"`
}

// A collection of values returned by getToken.
type LookupTokenResult struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
	// The time when the token was created.
	CreatedAt string `pulumi:"createdAt"`
	// A description of the token.
	Description string `pulumi:"description"`
	// The time when the token will expire.
	Expires string `pulumi:"expires"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of role IDs associated with the token.
	RoleIds []string `pulumi:"roleIds"`
	// The unique identifier of the Datafy token.
	TokenId string `pulumi:"tokenId"`
}

func LookupTokenOutput(ctx *pulumi.Context, args LookupTokenOutputArgs, opts ...pulumi.InvokeOption) LookupTokenResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTokenResultOutput, error) {
			args := v.(LookupTokenArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("datafy:index/getToken:getToken", args, LookupTokenResultOutput{}, options).(LookupTokenResultOutput), nil
		}).(LookupTokenResultOutput)
}

// A collection of arguments for invoking getToken.
type LookupTokenOutputArgs struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringInput `pulumi:"accountId"`
	// The unique identifier of the Datafy token.
	TokenId pulumi.StringInput `pulumi:"tokenId"`
}

func (LookupTokenOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTokenArgs)(nil)).Elem()
}

// A collection of values returned by getToken.
type LookupTokenResultOutput struct{ *pulumi.OutputState }

func (LookupTokenResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTokenResult)(nil)).Elem()
}

func (o LookupTokenResultOutput) ToLookupTokenResultOutput() LookupTokenResultOutput {
	return o
}

func (o LookupTokenResultOutput) ToLookupTokenResultOutputWithContext(ctx context.Context) LookupTokenResultOutput {
	return o
}

// The unique identifier of the Datafy account.
func (o LookupTokenResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.AccountId }).(pulumi.StringOutput)
}

// The time when the token was created.
func (o LookupTokenResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// A description of the token.
func (o LookupTokenResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.Description }).(pulumi.StringOutput)
}

// The time when the token will expire.
func (o LookupTokenResultOutput) Expires() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.Expires }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupTokenResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of role IDs associated with the token.
func (o LookupTokenResultOutput) RoleIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupTokenResult) []string { return v.RoleIds }).(pulumi.StringArrayOutput)
}

// The unique identifier of the Datafy token.
func (o LookupTokenResultOutput) TokenId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTokenResult) string { return v.TokenId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTokenResultOutput{})
}
