// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datafy

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "datafy:index/account:Account":
		r = &Account{}
	case "datafy:index/roleArn:RoleArn":
		r = &RoleArn{}
	case "datafy:index/token:Token":
		r = &Token{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:datafy" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"datafy",
		"index/account",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"datafy",
		"index/roleArn",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"datafy",
		"index/token",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"datafy",
		&pkg{version},
	)
}
