// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datafy

import (
	"context"
	"reflect"

	"errors"
	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a Datafy role ARN, which represents an AWS IAM role associated with a Datafy account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := datafy.NewRoleArn(ctx, "example", &datafy.RoleArnArgs{
//				AccountId: pulumi.String("5f19d868-64f2-4251-a98f-b19571d1f4e9"),
//				Arn:       pulumi.String("arn:aws:iam::123456789012:role/example-role"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type RoleArn struct {
	pulumi.CustomResourceState

	// The unique identifier of the Datafy account.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn pulumi.StringOutput `pulumi:"arn"`
}

// NewRoleArn registers a new resource with the given unique name, arguments, and options.
func NewRoleArn(ctx *pulumi.Context,
	name string, args *RoleArnArgs, opts ...pulumi.ResourceOption) (*RoleArn, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountId == nil {
		return nil, errors.New("invalid value for required argument 'AccountId'")
	}
	if args.Arn == nil {
		return nil, errors.New("invalid value for required argument 'Arn'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RoleArn
	err := ctx.RegisterResource("datafy:index/roleArn:RoleArn", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRoleArn gets an existing RoleArn resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRoleArn(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RoleArnState, opts ...pulumi.ResourceOption) (*RoleArn, error) {
	var resource RoleArn
	err := ctx.ReadResource("datafy:index/roleArn:RoleArn", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RoleArn resources.
type roleArnState struct {
	// The unique identifier of the Datafy account.
	AccountId *string `pulumi:"accountId"`
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn *string `pulumi:"arn"`
}

type RoleArnState struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringPtrInput
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn pulumi.StringPtrInput
}

func (RoleArnState) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArnState)(nil)).Elem()
}

type roleArnArgs struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn string `pulumi:"arn"`
}

// The set of arguments for constructing a RoleArn resource.
type RoleArnArgs struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringInput
	// The Amazon Resource Name (ARN) of the IAM role.
	Arn pulumi.StringInput
}

func (RoleArnArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArnArgs)(nil)).Elem()
}

type RoleArnInput interface {
	pulumi.Input

	ToRoleArnOutput() RoleArnOutput
	ToRoleArnOutputWithContext(ctx context.Context) RoleArnOutput
}

func (*RoleArn) ElementType() reflect.Type {
	return reflect.TypeOf((**RoleArn)(nil)).Elem()
}

func (i *RoleArn) ToRoleArnOutput() RoleArnOutput {
	return i.ToRoleArnOutputWithContext(context.Background())
}

func (i *RoleArn) ToRoleArnOutputWithContext(ctx context.Context) RoleArnOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArnOutput)
}

// RoleArnArrayInput is an input type that accepts RoleArnArray and RoleArnArrayOutput values.
// You can construct a concrete instance of `RoleArnArrayInput` via:
//
//	RoleArnArray{ RoleArnArgs{...} }
type RoleArnArrayInput interface {
	pulumi.Input

	ToRoleArnArrayOutput() RoleArnArrayOutput
	ToRoleArnArrayOutputWithContext(context.Context) RoleArnArrayOutput
}

type RoleArnArray []RoleArnInput

func (RoleArnArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RoleArn)(nil)).Elem()
}

func (i RoleArnArray) ToRoleArnArrayOutput() RoleArnArrayOutput {
	return i.ToRoleArnArrayOutputWithContext(context.Background())
}

func (i RoleArnArray) ToRoleArnArrayOutputWithContext(ctx context.Context) RoleArnArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArnArrayOutput)
}

// RoleArnMapInput is an input type that accepts RoleArnMap and RoleArnMapOutput values.
// You can construct a concrete instance of `RoleArnMapInput` via:
//
//	RoleArnMap{ "key": RoleArnArgs{...} }
type RoleArnMapInput interface {
	pulumi.Input

	ToRoleArnMapOutput() RoleArnMapOutput
	ToRoleArnMapOutputWithContext(context.Context) RoleArnMapOutput
}

type RoleArnMap map[string]RoleArnInput

func (RoleArnMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RoleArn)(nil)).Elem()
}

func (i RoleArnMap) ToRoleArnMapOutput() RoleArnMapOutput {
	return i.ToRoleArnMapOutputWithContext(context.Background())
}

func (i RoleArnMap) ToRoleArnMapOutputWithContext(ctx context.Context) RoleArnMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArnMapOutput)
}

type RoleArnOutput struct{ *pulumi.OutputState }

func (RoleArnOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RoleArn)(nil)).Elem()
}

func (o RoleArnOutput) ToRoleArnOutput() RoleArnOutput {
	return o
}

func (o RoleArnOutput) ToRoleArnOutputWithContext(ctx context.Context) RoleArnOutput {
	return o
}

// The unique identifier of the Datafy account.
func (o RoleArnOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *RoleArn) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// The Amazon Resource Name (ARN) of the IAM role.
func (o RoleArnOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *RoleArn) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

type RoleArnArrayOutput struct{ *pulumi.OutputState }

func (RoleArnArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RoleArn)(nil)).Elem()
}

func (o RoleArnArrayOutput) ToRoleArnArrayOutput() RoleArnArrayOutput {
	return o
}

func (o RoleArnArrayOutput) ToRoleArnArrayOutputWithContext(ctx context.Context) RoleArnArrayOutput {
	return o
}

func (o RoleArnArrayOutput) Index(i pulumi.IntInput) RoleArnOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RoleArn {
		return vs[0].([]*RoleArn)[vs[1].(int)]
	}).(RoleArnOutput)
}

type RoleArnMapOutput struct{ *pulumi.OutputState }

func (RoleArnMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RoleArn)(nil)).Elem()
}

func (o RoleArnMapOutput) ToRoleArnMapOutput() RoleArnMapOutput {
	return o
}

func (o RoleArnMapOutput) ToRoleArnMapOutputWithContext(ctx context.Context) RoleArnMapOutput {
	return o
}

func (o RoleArnMapOutput) MapIndex(k pulumi.StringInput) RoleArnOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RoleArn {
		return vs[0].(map[string]*RoleArn)[vs[1].(string)]
	}).(RoleArnOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArnInput)(nil)).Elem(), &RoleArn{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArnArrayInput)(nil)).Elem(), RoleArnArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArnMapInput)(nil)).Elem(), RoleArnMap{})
	pulumi.RegisterOutputType(RoleArnOutput{})
	pulumi.RegisterOutputType(RoleArnArrayOutput{})
	pulumi.RegisterOutputType(RoleArnMapOutput{})
}
