// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package datafy

import (
	"context"
	"reflect"

	"errors"
	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Create a Datafy token, which represents an access token associated with a Datafy account.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/braveokafor/pulumi-datafy/sdk/go/datafy"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := datafy.NewToken(ctx, "example", &datafy.TokenArgs{
//				AccountId:   pulumi.String("79c406c5-7b64-43f2-ba76-9b01e74e3d90"),
//				Description: pulumi.String("Example token"),
//				Ttl:         pulumi.String("60m"),
//				RoleIds: pulumi.StringArray{
//					pulumi.String("role1"),
//					pulumi.String("role2"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Token struct {
	pulumi.CustomResourceState

	// The unique identifier of the Datafy account.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// The time when the token was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// A description of the token.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The time when the token will expire.
	Expires pulumi.StringOutput `pulumi:"expires"`
	// A list of role IDs associated with the token.
	RoleIds pulumi.StringArrayOutput `pulumi:"roleIds"`
	// The secret value of the token.
	Secret pulumi.StringOutput `pulumi:"secret"`
	// The unique identifier of the Datafy token.
	TokenId pulumi.StringOutput `pulumi:"tokenId"`
	// The expiration time of the token.
	Ttl pulumi.StringPtrOutput `pulumi:"ttl"`
}

// NewToken registers a new resource with the given unique name, arguments, and options.
func NewToken(ctx *pulumi.Context,
	name string, args *TokenArgs, opts ...pulumi.ResourceOption) (*Token, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccountId == nil {
		return nil, errors.New("invalid value for required argument 'AccountId'")
	}
	if args.RoleIds == nil {
		return nil, errors.New("invalid value for required argument 'RoleIds'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Token
	err := ctx.RegisterResource("datafy:index/token:Token", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetToken gets an existing Token resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TokenState, opts ...pulumi.ResourceOption) (*Token, error) {
	var resource Token
	err := ctx.ReadResource("datafy:index/token:Token", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Token resources.
type tokenState struct {
	// The unique identifier of the Datafy account.
	AccountId *string `pulumi:"accountId"`
	// The time when the token was created.
	CreatedAt *string `pulumi:"createdAt"`
	// A description of the token.
	Description *string `pulumi:"description"`
	// The time when the token will expire.
	Expires *string `pulumi:"expires"`
	// A list of role IDs associated with the token.
	RoleIds []string `pulumi:"roleIds"`
	// The secret value of the token.
	Secret *string `pulumi:"secret"`
	// The unique identifier of the Datafy token.
	TokenId *string `pulumi:"tokenId"`
	// The expiration time of the token.
	Ttl *string `pulumi:"ttl"`
}

type TokenState struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringPtrInput
	// The time when the token was created.
	CreatedAt pulumi.StringPtrInput
	// A description of the token.
	Description pulumi.StringPtrInput
	// The time when the token will expire.
	Expires pulumi.StringPtrInput
	// A list of role IDs associated with the token.
	RoleIds pulumi.StringArrayInput
	// The secret value of the token.
	Secret pulumi.StringPtrInput
	// The unique identifier of the Datafy token.
	TokenId pulumi.StringPtrInput
	// The expiration time of the token.
	Ttl pulumi.StringPtrInput
}

func (TokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*tokenState)(nil)).Elem()
}

type tokenArgs struct {
	// The unique identifier of the Datafy account.
	AccountId string `pulumi:"accountId"`
	// A description of the token.
	Description *string `pulumi:"description"`
	// A list of role IDs associated with the token.
	RoleIds []string `pulumi:"roleIds"`
	// The expiration time of the token.
	Ttl *string `pulumi:"ttl"`
}

// The set of arguments for constructing a Token resource.
type TokenArgs struct {
	// The unique identifier of the Datafy account.
	AccountId pulumi.StringInput
	// A description of the token.
	Description pulumi.StringPtrInput
	// A list of role IDs associated with the token.
	RoleIds pulumi.StringArrayInput
	// The expiration time of the token.
	Ttl pulumi.StringPtrInput
}

func (TokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tokenArgs)(nil)).Elem()
}

type TokenInput interface {
	pulumi.Input

	ToTokenOutput() TokenOutput
	ToTokenOutputWithContext(ctx context.Context) TokenOutput
}

func (*Token) ElementType() reflect.Type {
	return reflect.TypeOf((**Token)(nil)).Elem()
}

func (i *Token) ToTokenOutput() TokenOutput {
	return i.ToTokenOutputWithContext(context.Background())
}

func (i *Token) ToTokenOutputWithContext(ctx context.Context) TokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenOutput)
}

// TokenArrayInput is an input type that accepts TokenArray and TokenArrayOutput values.
// You can construct a concrete instance of `TokenArrayInput` via:
//
//	TokenArray{ TokenArgs{...} }
type TokenArrayInput interface {
	pulumi.Input

	ToTokenArrayOutput() TokenArrayOutput
	ToTokenArrayOutputWithContext(context.Context) TokenArrayOutput
}

type TokenArray []TokenInput

func (TokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Token)(nil)).Elem()
}

func (i TokenArray) ToTokenArrayOutput() TokenArrayOutput {
	return i.ToTokenArrayOutputWithContext(context.Background())
}

func (i TokenArray) ToTokenArrayOutputWithContext(ctx context.Context) TokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenArrayOutput)
}

// TokenMapInput is an input type that accepts TokenMap and TokenMapOutput values.
// You can construct a concrete instance of `TokenMapInput` via:
//
//	TokenMap{ "key": TokenArgs{...} }
type TokenMapInput interface {
	pulumi.Input

	ToTokenMapOutput() TokenMapOutput
	ToTokenMapOutputWithContext(context.Context) TokenMapOutput
}

type TokenMap map[string]TokenInput

func (TokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Token)(nil)).Elem()
}

func (i TokenMap) ToTokenMapOutput() TokenMapOutput {
	return i.ToTokenMapOutputWithContext(context.Background())
}

func (i TokenMap) ToTokenMapOutputWithContext(ctx context.Context) TokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokenMapOutput)
}

type TokenOutput struct{ *pulumi.OutputState }

func (TokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Token)(nil)).Elem()
}

func (o TokenOutput) ToTokenOutput() TokenOutput {
	return o
}

func (o TokenOutput) ToTokenOutputWithContext(ctx context.Context) TokenOutput {
	return o
}

// The unique identifier of the Datafy account.
func (o TokenOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Token) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// The time when the token was created.
func (o TokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Token) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// A description of the token.
func (o TokenOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Token) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The time when the token will expire.
func (o TokenOutput) Expires() pulumi.StringOutput {
	return o.ApplyT(func(v *Token) pulumi.StringOutput { return v.Expires }).(pulumi.StringOutput)
}

// A list of role IDs associated with the token.
func (o TokenOutput) RoleIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Token) pulumi.StringArrayOutput { return v.RoleIds }).(pulumi.StringArrayOutput)
}

// The secret value of the token.
func (o TokenOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *Token) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

// The unique identifier of the Datafy token.
func (o TokenOutput) TokenId() pulumi.StringOutput {
	return o.ApplyT(func(v *Token) pulumi.StringOutput { return v.TokenId }).(pulumi.StringOutput)
}

// The expiration time of the token.
func (o TokenOutput) Ttl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Token) pulumi.StringPtrOutput { return v.Ttl }).(pulumi.StringPtrOutput)
}

type TokenArrayOutput struct{ *pulumi.OutputState }

func (TokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Token)(nil)).Elem()
}

func (o TokenArrayOutput) ToTokenArrayOutput() TokenArrayOutput {
	return o
}

func (o TokenArrayOutput) ToTokenArrayOutputWithContext(ctx context.Context) TokenArrayOutput {
	return o
}

func (o TokenArrayOutput) Index(i pulumi.IntInput) TokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Token {
		return vs[0].([]*Token)[vs[1].(int)]
	}).(TokenOutput)
}

type TokenMapOutput struct{ *pulumi.OutputState }

func (TokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Token)(nil)).Elem()
}

func (o TokenMapOutput) ToTokenMapOutput() TokenMapOutput {
	return o
}

func (o TokenMapOutput) ToTokenMapOutputWithContext(ctx context.Context) TokenMapOutput {
	return o
}

func (o TokenMapOutput) MapIndex(k pulumi.StringInput) TokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Token {
		return vs[0].(map[string]*Token)[vs[1].(string)]
	}).(TokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TokenInput)(nil)).Elem(), &Token{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenArrayInput)(nil)).Elem(), TokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TokenMapInput)(nil)).Elem(), TokenMap{})
	pulumi.RegisterOutputType(TokenOutput{})
	pulumi.RegisterOutputType(TokenArrayOutput{})
	pulumi.RegisterOutputType(TokenMapOutput{})
}
