# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .get_account import *
from .get_role_arn import *
from .get_token import *
from .provider import *
from .role_arn import *
from .token import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_datafy.config as __config
    config = __config
    import pulumi_datafy.region as __region
    region = __region
else:
    config = _utilities.lazy_import('pulumi_datafy.config')
    region = _utilities.lazy_import('pulumi_datafy.region')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "datafy",
  "mod": "index/account",
  "fqn": "pulumi_datafy",
  "classes": {
   "datafy:index/account:Account": "Account"
  }
 },
 {
  "pkg": "datafy",
  "mod": "index/roleArn",
  "fqn": "pulumi_datafy",
  "classes": {
   "datafy:index/roleArn:RoleArn": "RoleArn"
  }
 },
 {
  "pkg": "datafy",
  "mod": "index/token",
  "fqn": "pulumi_datafy",
  "classes": {
   "datafy:index/token:Token": "Token"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "datafy",
  "token": "pulumi:providers:datafy",
  "fqn": "pulumi_datafy",
  "class": "Provider"
 }
]
"""
)
