# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetTokenResult',
    'AwaitableGetTokenResult',
    'get_token',
    'get_token_output',
]

@pulumi.output_type
class GetTokenResult:
    """
    A collection of values returned by getToken.
    """
    def __init__(__self__, account_id=None, created_at=None, description=None, expires=None, id=None, role_ids=None, token_id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if expires and not isinstance(expires, str):
            raise TypeError("Expected argument 'expires' to be a str")
        pulumi.set(__self__, "expires", expires)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if role_ids and not isinstance(role_ids, list):
            raise TypeError("Expected argument 'role_ids' to be a list")
        pulumi.set(__self__, "role_ids", role_ids)
        if token_id and not isinstance(token_id, str):
            raise TypeError("Expected argument 'token_id' to be a str")
        pulumi.set(__self__, "token_id", token_id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        """
        The unique identifier of the Datafy account.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The time when the token was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        A description of the token.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def expires(self) -> _builtins.str:
        """
        The time when the token will expire.
        """
        return pulumi.get(self, "expires")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="roleIds")
    def role_ids(self) -> Sequence[_builtins.str]:
        """
        A list of role IDs associated with the token.
        """
        return pulumi.get(self, "role_ids")

    @_builtins.property
    @pulumi.getter(name="tokenId")
    def token_id(self) -> _builtins.str:
        """
        The unique identifier of the Datafy token.
        """
        return pulumi.get(self, "token_id")


class AwaitableGetTokenResult(GetTokenResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTokenResult(
            account_id=self.account_id,
            created_at=self.created_at,
            description=self.description,
            expires=self.expires,
            id=self.id,
            role_ids=self.role_ids,
            token_id=self.token_id)


def get_token(account_id: Optional[_builtins.str] = None,
              token_id: Optional[_builtins.str] = None,
              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTokenResult:
    """
    Retrieves a specific Datafy token.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_datafy as datafy

    example = datafy.get_token(account_id="79c406c5-7b64-43f2-ba76-9b01e74e3d90",
        token_id="7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6")
    ```


    :param _builtins.str account_id: The unique identifier of the Datafy account.
    :param _builtins.str token_id: The unique identifier of the Datafy token.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['tokenId'] = token_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('datafy:index/getToken:getToken', __args__, opts=opts, typ=GetTokenResult).value

    return AwaitableGetTokenResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        expires=pulumi.get(__ret__, 'expires'),
        id=pulumi.get(__ret__, 'id'),
        role_ids=pulumi.get(__ret__, 'role_ids'),
        token_id=pulumi.get(__ret__, 'token_id'))
def get_token_output(account_id: Optional[pulumi.Input[_builtins.str]] = None,
                     token_id: Optional[pulumi.Input[_builtins.str]] = None,
                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTokenResult]:
    """
    Retrieves a specific Datafy token.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_datafy as datafy

    example = datafy.get_token(account_id="79c406c5-7b64-43f2-ba76-9b01e74e3d90",
        token_id="7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6")
    ```


    :param _builtins.str account_id: The unique identifier of the Datafy account.
    :param _builtins.str token_id: The unique identifier of the Datafy token.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    __args__['tokenId'] = token_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('datafy:index/getToken:getToken', __args__, opts=opts, typ=GetTokenResult)
    return __ret__.apply(lambda __response__: GetTokenResult(
        account_id=pulumi.get(__response__, 'account_id'),
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        expires=pulumi.get(__response__, 'expires'),
        id=pulumi.get(__response__, 'id'),
        role_ids=pulumi.get(__response__, 'role_ids'),
        token_id=pulumi.get(__response__, 'token_id')))
