# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetRoleArnResult',
    'AwaitableGetRoleArnResult',
    'get_role_arn',
    'get_role_arn_output',
]

@pulumi.output_type
class GetRoleArnResult:
    """
    A collection of values returned by getRoleArn.
    """
    def __init__(__self__, account_id=None, arn=None, id=None):
        if account_id and not isinstance(account_id, str):
            raise TypeError("Expected argument 'account_id' to be a str")
        pulumi.set(__self__, "account_id", account_id)
        if arn and not isinstance(arn, str):
            raise TypeError("Expected argument 'arn' to be a str")
        pulumi.set(__self__, "arn", arn)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> _builtins.str:
        """
        The unique identifier of the Datafy account.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter
    def arn(self) -> _builtins.str:
        """
        The Amazon Resource Name (ARN) of the IAM role.
        """
        return pulumi.get(self, "arn")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetRoleArnResult(GetRoleArnResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRoleArnResult(
            account_id=self.account_id,
            arn=self.arn,
            id=self.id)


def get_role_arn(account_id: Optional[_builtins.str] = None,
                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRoleArnResult:
    """
    Retrieves a specific Datafy role ARN.


    :param _builtins.str account_id: The unique identifier of the Datafy account.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('datafy:index/getRoleArn:getRoleArn', __args__, opts=opts, typ=GetRoleArnResult).value

    return AwaitableGetRoleArnResult(
        account_id=pulumi.get(__ret__, 'account_id'),
        arn=pulumi.get(__ret__, 'arn'),
        id=pulumi.get(__ret__, 'id'))
def get_role_arn_output(account_id: Optional[pulumi.Input[_builtins.str]] = None,
                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRoleArnResult]:
    """
    Retrieves a specific Datafy role ARN.


    :param _builtins.str account_id: The unique identifier of the Datafy account.
    """
    __args__ = dict()
    __args__['accountId'] = account_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('datafy:index/getRoleArn:getRoleArn', __args__, opts=opts, typ=GetRoleArnResult)
    return __ret__.apply(lambda __response__: GetRoleArnResult(
        account_id=pulumi.get(__response__, 'account_id'),
        arn=pulumi.get(__response__, 'arn'),
        id=pulumi.get(__response__, 'id')))
