// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves a specific Datafy account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = datafy.getAccount({
 *     id: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
 * });
 * ```
 */
export function getAccount(args: GetAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datafy:index/getAccount:getAccount", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccount.
 */
export interface GetAccountArgs {
    /**
     * The unique identifier of the account.
     */
    id: string;
}

/**
 * A collection of values returned by getAccount.
 */
export interface GetAccountResult {
    /**
     * The unique identifier of the account.
     */
    readonly id: string;
    /**
     * The name of the account.
     */
    readonly name: string;
    /**
     * The unique identifier of the parent account
     */
    readonly parentAccountId: string;
}
/**
 * Retrieves a specific Datafy account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = datafy.getAccount({
 *     id: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
 * });
 * ```
 */
export function getAccountOutput(args: GetAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datafy:index/getAccount:getAccount", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccount.
 */
export interface GetAccountOutputArgs {
    /**
     * The unique identifier of the account.
     */
    id: pulumi.Input<string>;
}
