// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves a specific Datafy role ARN.
 */
export function getRoleArn(args: GetRoleArnArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleArnResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datafy:index/getRoleArn:getRoleArn", {
        "accountId": args.accountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRoleArn.
 */
export interface GetRoleArnArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: string;
}

/**
 * A collection of values returned by getRoleArn.
 */
export interface GetRoleArnResult {
    /**
     * The unique identifier of the Datafy account.
     */
    readonly accountId: string;
    /**
     * The Amazon Resource Name (ARN) of the IAM role.
     */
    readonly arn: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
/**
 * Retrieves a specific Datafy role ARN.
 */
export function getRoleArnOutput(args: GetRoleArnOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleArnResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datafy:index/getRoleArn:getRoleArn", {
        "accountId": args.accountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRoleArn.
 */
export interface GetRoleArnOutputArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: pulumi.Input<string>;
}
