// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Retrieves a specific Datafy token.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = datafy.getToken({
 *     accountId: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
 *     tokenId: "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
 * });
 * ```
 */
export function getToken(args: GetTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datafy:index/getToken:getToken", {
        "accountId": args.accountId,
        "tokenId": args.tokenId,
    }, opts);
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: string;
    /**
     * The unique identifier of the Datafy token.
     */
    tokenId: string;
}

/**
 * A collection of values returned by getToken.
 */
export interface GetTokenResult {
    /**
     * The unique identifier of the Datafy account.
     */
    readonly accountId: string;
    /**
     * The time when the token was created.
     */
    readonly createdAt: string;
    /**
     * A description of the token.
     */
    readonly description: string;
    /**
     * The time when the token will expire.
     */
    readonly expires: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A list of role IDs associated with the token.
     */
    readonly roleIds: string[];
    /**
     * The unique identifier of the Datafy token.
     */
    readonly tokenId: string;
}
/**
 * Retrieves a specific Datafy token.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = datafy.getToken({
 *     accountId: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
 *     tokenId: "7c4f5fcd-5a9c-4463-893a-9c2d09bf7bc6",
 * });
 * ```
 */
export function getTokenOutput(args: GetTokenOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datafy:index/getToken:getToken", {
        "accountId": args.accountId,
        "tokenId": args.tokenId,
    }, opts);
}

/**
 * A collection of arguments for invoking getToken.
 */
export interface GetTokenOutputArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: pulumi.Input<string>;
    /**
     * The unique identifier of the Datafy token.
     */
    tokenId: pulumi.Input<string>;
}
