// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Datafy role ARN, which represents an AWS IAM role associated with a Datafy account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = new datafy.RoleArn("example", {
 *     accountId: "5f19d868-64f2-4251-a98f-b19571d1f4e9",
 *     arn: "arn:aws:iam::123456789012:role/example-role",
 * });
 * ```
 */
export class RoleArn extends pulumi.CustomResource {
    /**
     * Get an existing RoleArn resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleArnState, opts?: pulumi.CustomResourceOptions): RoleArn {
        return new RoleArn(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datafy:index/roleArn:RoleArn';

    /**
     * Returns true if the given object is an instance of RoleArn.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RoleArn {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RoleArn.__pulumiType;
    }

    /**
     * The unique identifier of the Datafy account.
     */
    declare public readonly accountId: pulumi.Output<string>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role.
     */
    declare public readonly arn: pulumi.Output<string>;

    /**
     * Create a RoleArn resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleArnArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleArnArgs | RoleArnState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleArnState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["arn"] = state?.arn;
        } else {
            const args = argsOrState as RoleArnArgs | undefined;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.arn === undefined && !opts.urn) {
                throw new Error("Missing required property 'arn'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["arn"] = args?.arn;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RoleArn.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RoleArn resources.
 */
export interface RoleArnState {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId?: pulumi.Input<string>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role.
     */
    arn?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RoleArn resource.
 */
export interface RoleArnArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: pulumi.Input<string>;
    /**
     * The Amazon Resource Name (ARN) of the IAM role.
     */
    arn: pulumi.Input<string>;
}
