// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Create a Datafy token, which represents an access token associated with a Datafy account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as datafy from "@pulumi/datafy";
 *
 * const example = new datafy.Token("example", {
 *     accountId: "79c406c5-7b64-43f2-ba76-9b01e74e3d90",
 *     description: "Example token",
 *     ttl: "60m",
 *     roleIds: [
 *         "role1",
 *         "role2",
 *     ],
 * });
 * ```
 */
export class Token extends pulumi.CustomResource {
    /**
     * Get an existing Token resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TokenState, opts?: pulumi.CustomResourceOptions): Token {
        return new Token(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'datafy:index/token:Token';

    /**
     * Returns true if the given object is an instance of Token.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Token {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Token.__pulumiType;
    }

    /**
     * The unique identifier of the Datafy account.
     */
    declare public readonly accountId: pulumi.Output<string>;
    /**
     * The time when the token was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * A description of the token.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The time when the token will expire.
     */
    declare public /*out*/ readonly expires: pulumi.Output<string>;
    /**
     * A list of role IDs associated with the token.
     */
    declare public readonly roleIds: pulumi.Output<string[]>;
    /**
     * The secret value of the token.
     */
    declare public /*out*/ readonly secret: pulumi.Output<string>;
    /**
     * The unique identifier of the Datafy token.
     */
    declare public /*out*/ readonly tokenId: pulumi.Output<string>;
    /**
     * The expiration time of the token.
     */
    declare public readonly ttl: pulumi.Output<string | undefined>;

    /**
     * Create a Token resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TokenArgs | TokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TokenState | undefined;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["expires"] = state?.expires;
            resourceInputs["roleIds"] = state?.roleIds;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["tokenId"] = state?.tokenId;
            resourceInputs["ttl"] = state?.ttl;
        } else {
            const args = argsOrState as TokenArgs | undefined;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.roleIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleIds'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["description"] = args?.description;
            resourceInputs["roleIds"] = args?.roleIds;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["expires"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
            resourceInputs["tokenId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Token.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Token resources.
 */
export interface TokenState {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId?: pulumi.Input<string>;
    /**
     * The time when the token was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * A description of the token.
     */
    description?: pulumi.Input<string>;
    /**
     * The time when the token will expire.
     */
    expires?: pulumi.Input<string>;
    /**
     * A list of role IDs associated with the token.
     */
    roleIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The secret value of the token.
     */
    secret?: pulumi.Input<string>;
    /**
     * The unique identifier of the Datafy token.
     */
    tokenId?: pulumi.Input<string>;
    /**
     * The expiration time of the token.
     */
    ttl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Token resource.
 */
export interface TokenArgs {
    /**
     * The unique identifier of the Datafy account.
     */
    accountId: pulumi.Input<string>;
    /**
     * A description of the token.
     */
    description?: pulumi.Input<string>;
    /**
     * A list of role IDs associated with the token.
     */
    roleIds: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The expiration time of the token.
     */
    ttl?: pulumi.Input<string>;
}
